### ISSUE TITLE
Update doc to reflect availability of version 2.0.1

### ISSUE THREAD

**Issue by raoulschaffner** [NetAppDocs/nfs-plugin-vmware-vaai#5]
### Page URL

https://docs.netapp.com/us-en/nfs-plugin-vmware-vaai/releasenotes.html

### Page title

NetApp NFS Plug-in for VMware VAAI Release Notes

### Summary

please update the doc to reflect the fact that now 3 versions exist:
1.1.2
2.0
2.0.1
and maybe highlight the main differences between the versions and a compatibility matrix re: esxi versions.

thank you! :-)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @raoulschaffner, thank you for providing this feedback. We'll look into this and update the documentation accordingly.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed here:
https://library.netapp.com/ecm/ecm_download_file/ECMLP2875174
