### ISSUE TITLE
NFS Plug-in for VMware VAAI Release Notes link not working

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/nfs-plugin-vmware-vaai#6]
### Page URL

https://docs.netapp.com/us-en/nfs-plugin-vmware-vaai/releasenotes.html

### Page title

NetApp NFS Plug-in for VMware VAAI Release Notes

### Summary

The link to the NetApp NFS Plug-in for VMware VAAI Release Notes is not working.  The link on the page is: [NetApp NFS Plug-in for VMware VAAI Release Notes](https://library.netapp.com/ecm/ecm_download_file/ECMLP2875174)

The page that is opened for this link eventually returns this error:

Error:

OpenID Connect Provider error: Error in handling response type.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @DrKeno, I've checked and verified that the link is now working as expected. Thanks for highlighting this issue.
